[package]
edition = "2021"
name = "nzcp"
version = "0.1.0"

[dependencies]
base32 = "0.4.0"
chrono = "0.4.19"
serde = {version = "~1", features = ["derive"]}
serde_cbor = "0.11.2"
thiserror = "1"
uuid = {version = "0.8.2", features = ["serde"]}

[dev-dependencies]
serde_json = "~1"
